filter:
    paths:
        - app/*
    excluded_paths:
        - app/Schema/*
        - app/Template/*
        - app/Locale/*
        - app/Library/*
        - app/constants.php
        - app/common.php
        - app/check_setup.php
